Repository bigbomio/digital-contracts, pull requests merged in 2018-09, with the labels that each got.

#51 Refactoring documentation
  docs/.gitignore
  docs/DApps_Integration_Guide.md
  docs/Document_Sign_Technical_Paper.md
  docs/Freelancer_Smart_Contract_Architecture.md
  docs/Freelancer_Smart_Contract_Implement.md
  docs/Makefile
  docs/conf.py
  docs/contracts/AdminUpgradeabilityProxy.md
  docs/contracts/BBDocumentSign.md
  docs/contracts/BBFreelancer.md
  docs/contracts/BBFreelancerBid.md
  docs/contracts/BBFreelancerJob.md
  docs/contracts/BBFreelancerPayment.md
  docs/contracts/BBLib.md
  docs/contracts/BBParams.md
  docs/contracts/BBPoll.md
  docs/contracts/BBStandard.md
  docs/contracts/BBStorage.md
  docs/contracts/BBVoting.md
  docs/enviroments/mainnet.md
  docs/enviroments/ropsten.md
  docs/enviroments/tomo.md
  docs/images/Freelancer-High-level-Overview.png
  docs/images/Freelancer-Stack.png
  docs/images/ads-contracts-execution-tracking.png
  docs/images/ads-payment-flow.png
  docs/images/cpc_formula.svg
  docs/images/cpi_formula.svg
  docs/images/cpm_formula.svg
  docs/images/digital-contract-code-flow.png
  docs/images/digital_contract_sign_workflow.png
  docs/index.rst
  docs/make.bat
  technical-docs/images/.DS_Store
Labels: documentation, enhancement

#48 Dispute voting- Merge + add test case
  .gitignore
  src/contracts/BBPoll.sol
  src/coverage.json
  src/test/voting.js
  src/test/voting_with_against.js
  src/test/voting_with_no_against.js
Labels: enhancement

#34 Dispute voting implement
  .gitignore
  .travis.yml
  src/contracts/BBDispute.sol
  src/contracts/BBFreelancer.sol
  src/contracts/BBFreelancerBid.sol
  src/contracts/BBFreelancerJob.sol
  src/contracts/BBFreelancerPayment.sol
  src/contracts/BBLib.sol
  src/contracts/BBParams.sol
  src/contracts/BBStandard.sol
  src/contracts/BBVoting.sol
  src/coverage.json
  src/demo/contract-sign-ui/Archive.zip
  src/demo/contract-sign-ui/README.md
  src/demo/contract-sign-ui/package.json
  src/demo/contract-sign-ui/public/favicon.ico
  src/demo/contract-sign-ui/public/index.html
  src/demo/contract-sign-ui/public/manifest.json
  src/demo/contract-sign-ui/src/App.css
  src/demo/contract-sign-ui/src/App.js
  src/demo/contract-sign-ui/src/App.test.js
  src/demo/contract-sign-ui/src/api.json
  src/demo/contract-sign-ui/src/index.css
  src/demo/contract-sign-ui/src/index.js
  src/demo/contract-sign-ui/src/logo.svg
  src/demo/contract-sign-ui/src/registerServiceWorker.js
  src/test/digitalcontract.js
  src/test/freelancer.js
  src/test/storage.js
  src/test/voting.js
  src/test/voting_with_against.js
  src/test/voting_with_no_against.js
Labels: BBFreelancer
